ZSMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('landing_page.urls')),
    path('student-attendance/', include('attendance.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers-mangement/', include('teacher.urls')),
    path('students-mangement/', include('student.urls')),
    path('class-mangement/', include('classroom.urls')),
    path('library/', include('library.urls')),
    path('timetable/', include('timetable.urls')),
    path('adminstration/', include('schooladminstration.urls')),
    path('employee-management/', include('employee.urls')),
    path('finance-management/', include('finance.urls')),
    path('exam-management/', include('exams.urls')),
    path('school-calendar/', include('school_calendar.urls')),
    path('', include('subscription.urls')),
    path('parent/', include('parent.urls')),
    path('', include('text_to_voice.urls')),
    path('chat', include('chatapp.urls')),
    path('', include('search.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.urls import path
from . import views

app_name='employee'
urlpatterns = [
    path('employees-<uuid:school_id>/', views.employee_list, name='employee_list'),
    path('employees/profile-<int:employee_id>-<uuid:school_id>/', views.employee_profile, name='employee_profile'),
    path('salary_reconciliations-<uuid:school_id>/', views.payroll_reconciliation, name='reco'),
    path('salary_reconciliations/form-<uuid:school_id>', views.reconciliation_form, name='reco_form'),
    path('leave-list-<uuid:school_id>/', views.leave_list, name='leave'),
    path('leave-list/add-<uuid:school_id>/', views.leave_add, name='leave_add'),
    path('employees/profile-<int:employee_id>/update-<uuid:school_id>/', views.employee_update, name='employee_update'),
    path('dates-of-attendance-<uuid:school_id>/', views.employee_attendance_dates, name='employee_attendance_dates'),
    path('dates-of-attendance/mark-attendance-<int:att_id>-<uuid:school_id>/', views.mark_employee_attendance, name='mark_attendance'),
    path('dates-of-attendance/attendance-list-<int:att_id>-<uuid:school_id>/', views.attendance_list, name='attendance_list'),
    path('delete/<int:pk>-<uuid:school_id>/', views.employee_delete, name='employee_delete'),
]

# from django.urls import path
# from .views import EmployeeListCreateView, EmployeeRetrieveUpdateDestroyView

# urlpatterns = [
#     path('employees/', EmployeeListCreateView.as_view(), name='employee-list-create'),
#     path('employees/<int:pk>/', EmployeeRetrieveUpdateDestroyView.as_view(), name='employee-detail'),
# ]

finance/urls.py
from django.urls import path
from . import views

app_name='finance'

urlpatterns = [
    path('fees-categories-<uuid:school_id>/', views.fee_categories, name='fee_categories'),
    path('fees-categories/collection-<int:cate_id>-<uuid:school_id>/', views.fee_list, name='fee_list'),
    path('fees-<uuid:school_id>/', views.fee_list2, name='fee_list2'),
    
    path('fees-categories/collection-<int:cate_id>/payments<int:fee_id>-<uuid:school_id>/', views.fee_payments, name='fee_payments'),
    path('fees-categories/other-fee-payments<int:fee_id>-<uuid:school_id>/', views.other_fee_payments, name='other_fee_payments'),
    path('fees-categories/collection-<int:cate_id>/payments<int:fee_id>/add_payment-<uuid:school_id>/', views.add_payment, name='add_payment'),
    path('fees-categories/other-fee-payments/add-<int:fee_id>/add_payment-<uuid:school_id>/', views.add_other_payment, name='add_other_payment'),
    
    path('financial-reports-<uuid:school_id>/', views.finance_reports, name='financial_reports'),
    # path('fees/delete/<int:pk>/', views.fee_delete, name='fee_delete'),
    # path('payments/', views.payment_list, name='payment_list'),
    # path('payments/add/', views.payment_add, name='payment_add'),
    # path('payments/update/<int:pk>/', views.payment_update, name='payment_update'),
    # path('payments/delete/<int:pk>/', views.payment_delete, name='payment_delete'),
    
    # Payroll URLs
    path('payrolls/<uuid:school_id>/', views.payroll_list, name='payroll_list'),
    path('Advance-salary-payments-<uuid:school_id>/', views.advance_payroll_list, name='ad_payroll_list'),
    path('Advance-salary-payments/add-<uuid:school_id>/', views.advance_payroll_form, name='add_advance'),
    path('payrolls/add-<uuid:school_id>/', views.payroll_form, name='payroll_add'),
    # path('payrolls/update/<int:pk>/', views.payroll_update, name='payroll_update'),
    # path('payrolls/delete/<int:pk>/', views.payroll_delete, name='payroll_delete'),
    
    # Expense URLs
    path('expenses-income-<uuid:school_id>/', views.income_expense, name='income_expense'),
    path('invoicing-<uuid:school_id>/', views.invoicing, name='invoicing'),
    path('invoicing/invoice-add-<uuid:school_id>/', views.invoice_add, name='invoice_add'),
    path('invoicing/invoice-view-<int:inv_id>-<uuid:school_id>/', views.invoice_view, name='invoice_view'),
    # path('expenses/update/<int:pk>/', views.expense_update, name='expense_update'),
    # path('expenses/delete/<int:pk>/', views.expense_delete, name='expense_delete'),
]

student/urls.py
from django.urls import path
from .views import *

app_name='student'
urlpatterns = [
    path('students-<uuid:school_id>/', students, name='students'),
    path('students/add-enroll-<uuid:school_id>/', student_form, name='student_form'),
    path('students/<int:stu_id>-<uuid:school_id>/', single_student, name='student'),
    path('students/update/<int:stu_id>-<uuid:school_id>/', student_update, name='update'),
    path('student/exams-<int:student_id>-<uuid:school_id>/', exams, name='exams'),
    path('student/exam-result-<int:student_id>-<uuid:school_id>/', exam_result, name='exam_result'),
    path('student/attendance-<int:student_id>-<uuid:school_id>/', attendance, name='atte'),
    path('student/assignments-<int:student_id>-<uuid:school_id>/', assignments, name='ass'),
    path('student/book-checkouts-<int:student_id>-<uuid:school_id>/', book_checkouts, name='check_outs')
]

employee/models.py
from django.db import models
from schooladminstration.models import Institution
from teacher.models import Instructor
from django.utils import timezone
# Create your models here.

class Employee(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='employees')
    teacher=models.ForeignKey(Instructor, on_delete=models.DO_NOTHING, related_name='employee', null=True, blank=True, default=None)
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    sex=(
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    gender=models.CharField(max_length=10, choices=sex)
    date_of_birth=models.DateField(null=True, blank=True, default=None)
    phone=models.IntegerField(null=True, blank=True, default=None)
    address=models.TextField(null=True, blank=True, default=None)
    position=models.CharField(max_length=20)
    salary = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, default=None)
    date_of_hire = models.DateField(null=True, blank=True, default=None)

    EMPLOYMENT_STATUS = [
        ('FT', 'Full-Time'),
        ('PT', 'Part-Time'),
        ('CON', 'Contract'),
        ('SUB', 'Substitute'),
    ]
    employment_status = models.CharField(max_length=3, choices=EMPLOYMENT_STATUS, default=None, blank=True, null=True)
    
    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.position}'
    
    def needs_attention(self):
        fields=[self.address, self.salary, self.date_of_hire, self.date_of_birth, self.employment_status]
        if None in fields:
            return True
        return False

class Document(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='employee_documents')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    DOC_TYPE = [
        ('CV', 'cv'),
        ('Identification Card', 'identification card'),
        ('Contract', 'contract'),
        ('Certification', 'certification'),
        ('Other', 'other'),
    ]
    doc_type = models.CharField(max_length=100, choices=DOC_TYPE)  # e.g., contract, ID, certification
    document = models.FileField(upload_to='school_files/employee_documents/')
    def __str__(self):
        return f"{self.doc_type} - {self.employee.first_name, self.employee.last_name}"
    
class AttendanceDate(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='employee_attendance_dates')
    date = models.DateField(default=timezone.now, unique=True)
    def employees_attended(self):
        atte=self
        n=atte.employee_attendance.filter(status='present')
        return n.count()

    def employees_absent(self):
        atte=self
        n=atte.employee_attendance.filter(status='absent')
        return n.count()
    
    def employees_late(self):
        atte=self
        n=atte.employee_attendance.filter(status='late')
        return n.count()

class EmployeeAttendance(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='employee_attendance')
    attendance_date=models.ForeignKey(AttendanceDate, on_delete=models.CASCADE, related_name='employee_attendance', default=None, blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    status = models.CharField(max_length=10, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')])
    processed=models.BooleanField(default=False)


class LeaveRequest(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='leaves')
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    leave_status = models.CharField(max_length=20, default=None, choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('personal', 'Personal')])
    leave_type = models.CharField(max_length=20, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')])
    start_date = models.DateField()
    end_date = models.DateField(default=None, null=True, blank=True)
    status = models.CharField(max_length=10, default='Approved', choices=[('Pending', 'Pending'), ('Approved', 'Approved'),  ('Rejected', 'Rejected'), ('Returned', 'Returned')])
    processed=models.BooleanField(default=False)
    date_returned=models.DateField(default=None, null=True, blank=True)
    def total_days(self):
        if self.end_date:
            return (self.end_date - self.start_date).days + 1
        return 'unknown'
    

employee/forms.py

from django import forms
from .models import AttendanceDate, Employee, Document, LeaveRequest

class EmployeeForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        # label='Date started working',
        # help_text='e.g 32 inch, 40 inch, 50 inch',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'type':'date'
            }
        )
    )
    date_of_hire = forms.DateField(
        label='Date started working',
        # help_text='e.g 32 inch, 40 inch, 50 inch',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'type':'date'
            }
        )
    )
    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'gender', 'date_of_birth', 'phone', 'address', 'position', 'employment_status', 'salary', 'date_of_hire']
    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class':'form-control'})
        self.fields['last_name'].widget.attrs.update({'class':'form-control'})
        self.fields['gender'].widget.attrs.update({'class':'form-control selectric'})
        self.fields['phone'].widget.attrs.update({'class':'form-control'})
        self.fields['position'].widget.attrs.update({'class':'form-control'})
        self.fields['employment_status'].widget.attrs.update({'class':'form-control selectric'})
        self.fields['address'].widget.attrs.update({'class':'form-control'})
        self.fields['salary'].widget.attrs.update({'class':'form-control'})
        for fields2 in ['gender','first_name','last_name','position', 'date_of_birth', 'phone', 'address', 'salary', 'date_of_hire']:
            self.fields[fields2].help_text=None

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['doc_type', 'document']
    def __init__(self, *args, **kwargs):
        super(DocumentForm, self).__init__(*args, **kwargs)
        self.fields['doc_type'].widget.attrs.update({'class':'form-control'})
        self.fields['document'].widget.attrs.update({'class':'form-control'})

class AttendanceDateForm(forms.ModelForm):
    date = forms.DateField(
        label='Date Of Attendance',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'type':'date'
            }
        )
    )
    class Meta:
        model = AttendanceDate
        fields = ['date',]

class leaveForm(forms.ModelForm):
    start_date = forms.DateField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'type':'date'
            }
        )
    )
    end_date = forms.DateField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'type':'date'
            }
        )
    )
    class Meta:
        model = LeaveRequest
        fields = ['employee','leave_status', 'leave_type', 'start_date', 'end_date']
    def __init__(self, *args, **kwargs):
        super(leaveForm, self).__init__(*args, **kwargs)
        self.fields['employee'].widget.attrs.update({'class':'form-control select2'})
        self.fields['leave_status'].widget.attrs.update({'class':'form-control selectric'})
        self.fields['leave_type'].widget.attrs.update({'class':'form-control selectric'})
        self.fields['start_date'].widget.attrs.update({'class':'form-control'})
        self.fields['end_date'].widget.attrs.update({'class':'form-control'})
      

templates/templates/employee/attendance_dates.html
{% extends 'templates/main/base.html' %}
{% load widget_tweaks %}
{% block title %}

{% endblock %}

{% block content %}

<section class="section">
  <div class="section-body">
  <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
              <h4 class="d-inline"> Employee Attendance</h4>
              <div class="card-header-action">
                <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                  Mark Attendance
                </button>
                
              </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-striped table-hover" id="save-stage" style="width:100%;">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Attended</th>
                    <th>Late</th>
                    <th>Absent</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for d in attendance_dates %}
                  <tr>
                  
                      <td>
                        {{d.date}}
                      </td>
                      <td>
                        <span class="badge badge-success">{{d.employees_attended}}</span>                         
                      </td>
                      <td>
                        <span class="badge badge-warning">{{d.employees_late}}</span>
                      </td>
                      <td>
                        <span class="badge badge-danger">{{d.employees_absent}}</span>
                      </td>
                      <td><a href="{% url 'employee:attendance_list' d.id school_id %}" class="btn btn-primary">Attendance</a></td>
  
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </section>


<!-- Add student modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Attendance Date</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="" method="post" class="">
          {% csrf_token %}
          <div class="modal-body">

              {{form.as_table}}
              
          
          </div>
          <div class="modal-footer bg-whitesmoke br">
            <button id="submit_btn" type="submit" class="btn btn-primary">Start Marking</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/templates/employee/leave_employees.html
{% extends 'templates/main/base.html' %}

{% block title %}
employees list
{% endblock %}

{% block content %}
<section class="section">
<div class="section-body">
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Leave </h4>
            <div class="card-header-action">
              <!-- <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add Payroll
              </button> -->
              <a href="{% url 'employee:leave_add' school_id %}" class="btn btn-info">Add</a>
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" id="tableExport" style="width:100%;">
              <thead>
                <tr>
                    <th>Employee</th>
                    <th>Status</th>
                    <th>Type</th>
                    <th>Period</th>
                    <!-- <th>Net Salary</th>
                    <th>Paid Date</th> -->
                    <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for leave in leaves %}
                <tr>
                    <td>{{ leave.employee }}</td>
                    <td>{{ leave.leave_status }}</td>
                    <td>{{ leave.leave_type }}</td>
                    <td>{{ leave.start_date }} - {{leave.end_date}} ({{leave.total_days}})</td>
                    <!-- <td>{{ payroll.net_salary }}</td>
                    <td>{{ payroll.payment_date }}</td> -->
                    <td></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

<!-- Add student modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add Employee</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form id="" method="post" class="">
          {% csrf_token %}
          <div class="modal-body">
            <label for="id_employee">Employee</label>
              <select name="employee" id="id_employee" class="form-control selectric" required>
                <option value="">Select Employee</option>
                {% for employee in employees %}
                  {% if employee.payroll.all %}
                    {% for payroll in employee.payroll.all %}
                      {% if payroll.year == year and payroll.month == month %}
                      {% else %}
                      <option value="{{employee.id}}">{{payroll}} {{employee.first_name}} - {{employee.position}}</option>
                      {% endif %}
                    {% endfor %}
                  {% else %}
                  <option value="{{employee.id}}">{{payroll}} {{employee.first_name}} - {{employee.position}}</option>
                  {% endif %}
                {% endfor %}
              </select>
              
              {{form}}
          </div>
          <div class="modal-footer bg-whitesmoke br">
            <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
  
  $('#id_employee').on('change', function(){
    $.ajax({
            type:'POST',
            url:'{% url "finance:payroll_list" school_id %}',
            data: {
                employee:$('#id_employee').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        
            },
            success: function(data){
              $('#id_salary').val(`${data.salary}`);
            },
    });
  });

</script>
{% endblock %}

templates/templates/employee/mark_attendance.html
{% extends 'templates/main/base.html' %}
{% load widget_tweaks %}
{% block title %}

{% endblock %}

{% block content %}
<section class="section">
<div class="section-body">
<div class="row">
    <div class="col-12">
      <div class="card">
        <form method="post" action="">
        <div class="card-header">
            <h4 class="d-inline">Mark Employee Attendance</h4>
            
            <div class="card-header-action">
              <button type="submit" class="btn btn-primary">
                Save Data
              </button>
            </div>
        </div>
        <div class="card-body"> 
          {% if already_marked %}
          <div class="text-center">
            <h5>Looks like attendance for <span class="mute">{{subject}}</span> has already been marked</h5>
          </div>
          {% else %}
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody style="overflow: scroll !important;">
                {% csrf_token %}

                {% for student in employees %}
               
                <tr>
                  <td>{{student.first_name|title}} {{student.last_name|title}}</td>

                  <td>
                   
                    <select name="status" id="id_status" class="form-control select2" style="width: 100%;" required>
                      <option value="present">Present</option>
                      <option value="absent">Absent</option>
                      <option value="late">Late</option>
                    </select>
                    <input type="text" value="{{student.id}}" name="employee" hidden>
                  </td>
                  <td><a href="{% url 'employee:employee_profile' student.id school_id %}" class="btn btn-primary">View</a></td>
                </tr>
                
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% endif %}
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
</section>

<!-- Add student modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add Student</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form id="" method="post" class="">
          {% csrf_token %}
          <div class="modal-body">

              {{form.as_table}}
              
              {{form2.as_table}}
          
          </div>
          <div class="modal-footer bg-whitesmoke br">
            <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
      
      $(document).on('submit', '#student_form', function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "student:students" school_id %}',
            data: {
                fname:$('#id_first_name').val(),
                lname:$('#id_last_name').val(),
                gender:$('#id_gender').val(),
                id_number:$('#id_id_number').val(),
                phone:$('#id_phone').val(),
                address:$('#id_address').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                fun: function(){
                  $('.loader-div>i').addClass('fa fa-gear fa-spin')

                  $("#submit_btn").replaceWith(
                    `
                    <button id='submit_btn' type="submit" class="btn btn-primary disabled" disabled="true">
                      <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> 
                    </button>
                    `
                  );

                }
            },
            success: function(status){
              $("#login_btn").replaceWith(
                    `
                    <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
                    `
                  );

            },
  
        });
    });
</script>
{% endblock %}

templates/templates/employee/reconciliation.html
{% extends 'templates/main/base.html' %}

{% block title %}
employees list
{% endblock %}

{% block content %}
<section class="section">
<div class="section-body">
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Payroll Reconciliation</h4>
            <div class="card-header-action">
              <!-- <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add Payroll
              </button> -->
              <a href="{% url 'employee:reco_form' school_id %}" class="btn btn-info">Add Reconciliation</a>
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" id="tableExport" style="width:100%;">
              <thead>
                <tr>
                    <th>Employee</th>
                    <!-- <th>Gross Salary</th> -->
                    <th>Allowance</th>
                    <th>Deductions</th>
                    <!-- <th>Net Salary</th>
                    <th>Paid Date</th> -->
                    <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for payroll in reconciliation %}
                <tr>
                    <td>{{ payroll.employee }}</td>
                    <!-- <td>{{ payroll.gross_salary }}</td> -->
                    <td>{{ payroll.allowances }}</td>
                    <td>{{ payroll.dedactions }}</td>
                    <!-- <td>{{ payroll.net_salary }}</td>
                    <td>{{ payroll.payment_date }}</td> -->
                    <td></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

<!-- Add student modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add Employee</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form id="" method="post" class="">
          {% csrf_token %}
          <div class="modal-body">
            <label for="id_employee">Employee</label>
              <select name="employee" id="id_employee" class="form-control selectric" required>
                <option value="">Select Employee</option>
                {% for employee in employees %}
                  {% if employee.payroll.all %}
                    {% for payroll in employee.payroll.all %}
                      {% if payroll.year == year and payroll.month == month %}
                      {% else %}
                      <option value="{{employee.id}}">{{payroll}} {{employee.first_name}} - {{employee.position}}</option>
                      {% endif %}
                    {% endfor %}
                  {% else %}
                  <option value="{{employee.id}}">{{payroll}} {{employee.first_name}} - {{employee.position}}</option>
                  {% endif %}
                {% endfor %}
              </select>
              
              {{form}}
          </div>
          <div class="modal-footer bg-whitesmoke br">
            <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
  
  $('#id_employee').on('change', function(){
    $.ajax({
            type:'POST',
            url:'',
            data: {
                employee:$('#id_employee').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        
            },
            success: function(data){
              $('#id_salary').val(`${data.salary}`);
            },
    });
  });

</script>
{% endblock %}