ZSMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('landing_page.urls')),
    path('student-attendance/', include('attendance.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers-mangement/', include('teacher.urls')),
    path('students-mangement/', include('student.urls')),
    path('class-mangement/', include('classroom.urls')),
    path('library/', include('library.urls')),
    path('timetable/', include('timetable.urls')),
    path('adminstration/', include('schooladminstration.urls')),
    path('employee-management/', include('employee.urls')),
    path('finance-management/', include('finance.urls')),
    path('exam-management/', include('exams.urls')),
    path('school-calendar/', include('school_calendar.urls')),
    path('', include('subscription.urls')),
    path('parent/', include('parent.urls')),
    path('', include('text_to_voice.urls')),
    path('chat', include('chatapp.urls')),
    path('', include('search.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finance/urls.py
from django.urls import path
from . import views

app_name='finance'

urlpatterns = [
    path('fees-categories-<uuid:school_id>/', views.fee_categories, name='fee_categories'),
    path('fees-categories/collection-<int:cate_id>-<uuid:school_id>/', views.fee_list, name='fee_list'),
    path('fees-<uuid:school_id>/', views.fee_list2, name='fee_list2'),
    
    path('fees-categories/collection-<int:cate_id>/payments<int:fee_id>-<uuid:school_id>/', views.fee_payments, name='fee_payments'),
    path('fees-categories/other-fee-payments<int:fee_id>-<uuid:school_id>/', views.other_fee_payments, name='other_fee_payments'),
    path('fees-categories/collection-<int:cate_id>/payments<int:fee_id>/add_payment-<uuid:school_id>/', views.add_payment, name='add_payment'),
    path('fees-categories/other-fee-payments/add-<int:fee_id>/add_payment-<uuid:school_id>/', views.add_other_payment, name='add_other_payment'),
    
    path('financial-reports-<uuid:school_id>/', views.finance_reports, name='financial_reports'),
    # path('fees/delete/<int:pk>/', views.fee_delete, name='fee_delete'),
    # path('payments/', views.payment_list, name='payment_list'),
    # path('payments/add/', views.payment_add, name='payment_add'),
    # path('payments/update/<int:pk>/', views.payment_update, name='payment_update'),
    # path('payments/delete/<int:pk>/', views.payment_delete, name='payment_delete'),
    
    # Payroll URLs
    path('payrolls/<uuid:school_id>/', views.payroll_list, name='payroll_list'),
    path('Advance-salary-payments-<uuid:school_id>/', views.advance_payroll_list, name='ad_payroll_list'),
    path('Advance-salary-payments/add-<uuid:school_id>/', views.advance_payroll_form, name='add_advance'),
    path('payrolls/add-<uuid:school_id>/', views.payroll_form, name='payroll_add'),
    # path('payrolls/update/<int:pk>/', views.payroll_update, name='payroll_update'),
    # path('payrolls/delete/<int:pk>/', views.payroll_delete, name='payroll_delete'),
    
    # Expense URLs
    path('expenses-income-<uuid:school_id>/', views.income_expense, name='income_expense'),
    path('invoicing-<uuid:school_id>/', views.invoicing, name='invoicing'),
    path('invoicing/invoice-add-<uuid:school_id>/', views.invoice_add, name='invoice_add'),
    path('invoicing/invoice-view-<int:inv_id>-<uuid:school_id>/', views.invoice_view, name='invoice_view'),
    # path('expenses/update/<int:pk>/', views.expense_update, name='expense_update'),
    # path('expenses/delete/<int:pk>/', views.expense_delete, name='expense_delete'),
]

student/urls.py
from django.urls import path
from .views import *

app_name='student'
urlpatterns = [
    path('students-<uuid:school_id>/', students, name='students'),
    path('students/add-enroll-<uuid:school_id>/', student_form, name='student_form'),
    path('students/<int:stu_id>-<uuid:school_id>/', single_student, name='student'),
    path('students/update/<int:stu_id>-<uuid:school_id>/', student_update, name='update'),
    path('student/exams-<int:student_id>-<uuid:school_id>/', exams, name='exams'),
    path('student/exam-result-<int:student_id>-<uuid:school_id>/', exam_result, name='exam_result'),
    path('student/attendance-<int:student_id>-<uuid:school_id>/', attendance, name='atte'),
    path('student/assignments-<int:student_id>-<uuid:school_id>/', assignments, name='ass'),
    path('student/book-checkouts-<int:student_id>-<uuid:school_id>/', book_checkouts, name='check_outs')
]

finance/models.py
from django.db import models
from employee.models import Employee
from school_calendar.models import AcademicYear, Term
from schooladminstration.models import Institution
from student.models import Enrollment, Student
from teacher.models import Instructor

# Create your models here.


class FeeCategory(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='fee_categories')
    title=models.CharField(max_length=50)
    enrollment=models.ManyToManyField(Enrollment, related_name='fee_category')
    description=models.TextField(null=True, blank=True, default=None)
    def __str__(self):
        return self.title

class Fee(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fees')
    fee_title=models.CharField(max_length=50, null=True, blank=True, default=None)
    fee_category=models.ForeignKey(FeeCategory, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fees')
    term=models.ForeignKey(Term, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fees')
    academic_year=models.ForeignKey(AcademicYear, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fees')
    fee_amount=models.DecimalField(max_digits=10, decimal_places=2, default=0)
    due_date=models.DateField()
    p=(
        ('once off', 'Once Off'),
        ('per month', 'Per Month'),
        ('per term', 'Per Term'),
        ('per semister', 'Per Semister'),
        ('per year', 'Per Year')
    )
    period=models.CharField(max_length=20, choices=p, default='per term', null=True, blank=True)
    closed=models.BooleanField(default=False)
    date=models.DateField(auto_now_add=True, null=True, blank=True)
    class Meta:
        ordering=['-date']
        unique_together=['term', 'academic_year']
    
    def __str__(self):
        return f'Tuition fee({self.fee_category.title}) - {self.fee_amount}'
    
class OtherFee(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='other_fees')
    fee_title=models.CharField(max_length=50, null=True, blank=True, default=None)
    enrollment=models.ManyToManyField(Enrollment, related_name='other_fees',  null=True, blank=True, default=None)
    p=(
        ('once off', 'Once Off'),
        ('per month', 'Per Month'),
        ('per term', 'Per Term'),
        ('per semister', 'Per Semister'),
        ('per year', 'Per Year')
    )
    period=models.CharField(max_length=20, choices=p)
    fee_amount=models.DecimalField(max_digits=10, decimal_places=2, default=0)
    # due_date=models.DateField()
    closed=models.BooleanField(default=False)
    date=models.DateField(auto_now_add=True, null=True, blank=True)
    class Meta:
        ordering=['-date']
    
    def __str__(self):
        return f'{self.fee_title } - MK{self.fee_amount} {self.period}'
    
class FeePayment(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fee_payments')
    academic_year=models.ForeignKey(AcademicYear, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fee_payments')
    term=models.ForeignKey(Term, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fee_payments')
    student=models.ForeignKey(Student, on_delete=models.CASCADE, related_name='fee_payments')
    fee=models.ForeignKey(Fee, on_delete=models.CASCADE , related_name='fee_payments', null=True, blank=True, default=None)
    other_fee=models.ForeignKey(OtherFee, on_delete=models.CASCADE , related_name='other_fee_payments', null=True, blank=True, default=None)
    amount_paid=models.DecimalField(max_digits=10, decimal_places=2)
    fully_paid=models.BooleanField(default=False)
    payment_date=models.DateField(auto_now_add=True, null=True, blank=True)
    class Meta:
        ordering=['-payment_date']
    
    def __str__(self):
        return f'Payment of {self.amount_paid} for {self.student.first_name}'
    
    def save(self, *args, **kwargs):
        if self.amount_paid and self.fee:
            if self.amount_paid >= self.fee.fee_amount:
                self.fully_paid=True
        elif self.amount_paid and self.other_fee:
            if self.amount_paid >= self.other_fee.fee_amount:
                self.fully_paid=True
        super(FeePayment, self).save(*args, **kwargs)
        
    def is_fully_paid(self):
        student_payments=self.student.fee_payments.filter(fee=self.fee)
        total=0
        for payment in student_payments:
            amount=payment.amount_paid
            total=+amount
        if total>=self.fee.fee_amount:
            return True
        else:
            return False
    
    def balance(self):
        if self.fee:
            student_payments=self.student.fee_payments.filter(fee=self.fee)
            total=0
            for payment in student_payments:
                amount=payment.amount_paid
                total=+amount
            return self.fee.fee_amount-total
        elif self.other_fee:
            student_payments=self.student.fee_payments.filter(other_fee=self.other_fee)
            total=0
            for payment in student_payments:
                amount=payment.amount_paid
                total=+amount
            return self.other_fee.fee_amount-total
    
class Invoice(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='invoices')
    academic_year=models.ForeignKey(AcademicYear, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='invoices')
    term=models.ForeignKey(Term, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='invoices')
    student=models.ForeignKey(Student, on_delete=models.CASCADE, related_name='invoices')
    fee=models.ForeignKey(Fee, on_delete=models.CASCADE , related_name='invoices')
    other_fee=models.ManyToManyField(OtherFee, related_name='invoices', null=True, blank=True, default=None)
    issue_discount=models.BooleanField(default=False)
    discount_percentage=models.IntegerField(max_length=2, null=True, blank=True, default=None)
    discount_amount=models.DecimalField(max_digits=10, decimal_places=2, default=False, null=True, blank=True)
    
    def __str__(self):
        return f'Invoice for {self.student}'
    
    def tuition_fee_amount(self):
        return self.fee.fee_amount
    
    def other_fee_amount(self):
        total=0
        for d in self.other_fee.all():
            total+=d.fee_amount
        return total
    
    def total_fees(self):
        return self.tuition_fee_amount()+self.other_fee_amount()
    
    def amount_paid(self):
        payments=FeePayment.objects.filter(student=self.student, academic_year=self.academic_year, term=self.term)
        total=0
        for payment in payments:
            total+=payment.amount_paid
        return total

    def after_discount_fee(self):
        if self.issue_discount:
            total=self.total_fees()
            dis=total*self.discount_percentage/100
            return total-dis
        
    def fee_balance(self):
        if self.issue_discount:
            b=self.after_discount_fee()-self.amount_paid()
            return b
        b=self.total_fees()-self.amount_paid()
        return b

class FeePaymentHistory(models.Model):
    school=models.ForeignKey(Institution, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='fee_payments_history')
    fee_payment=models.ForeignKey(FeePayment, on_delete=models.CASCADE, related_name='fee_payments_history')
    amount_paid=models.DecimalField(max_digits=10, decimal_places=2)
    payment_date=models.DateField(auto_now_add=True)
    class Meta:
        ordering=['-payment_date']
    
    def __str__(self):
        return f'Payment of {self.amount_paid}'
    
    def save(self, *args, **kwargs):
        self.amount_paid=self.fee_payment.amount_paid
        self.save()
        super(FeePaymentHistory, self).save(*args, **kwargs)
    
    
class Income(models.Model):
    institution=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='incomes')
    academic_year=models.ForeignKey(AcademicYear, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='incomes')
    term=models.ForeignKey(Term, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='incomes')
    source=models.CharField(max_length=50)
    description=models.TextField()
    amount=models.DecimalField(max_digits=10, decimal_places=2)
    date=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    date_incurred=models.DateField(null=True, blank=True, default=None)
    class Meta:
        ordering=['-date']
    def __str__(self):
        return f'{self.source} - {self.amount}'
    
class Expense(models.Model):
    institution=models.ForeignKey(Institution, on_delete=models.CASCADE, related_name='expenses')
    academic_year=models.ForeignKey(AcademicYear, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='expenses')
    term=models.ForeignKey(Term, on_delete=models.CASCADE, null=True, blank=True, default=None, related_name='expenses')
    description=models.TextField()
    amount=models.DecimalField(max_digits=10, decimal_places=2)
    date=models.DateTimeField(auto_now_add=True, null=True, blank=True)
    date_incurred=models.DateField(null=True, blank=True, default=None)
    class Meta:
        ordering=['-date']
    def __str__(self):
        return f'{self.description} - {self.amount}'
    
class PayrollReconciliation(models.Model):

templates/templates/finance/fee_categories.html

{% extends 'templates/main/base.html' %}

{% block title %}
employees list
{% endblock %}

{% block content %}
<section class="section">
<div class="section-body">

  <ul class="nav nav-tabs" id="myTab2" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab2" data-toggle="tab" href="#home2" role="tab"
        aria-controls="home" aria-selected="true">Fees Categories</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab2" data-toggle="tab" href="#profile2" role="tab"
        aria-controls="profile" aria-selected="false">Additional fees</a>
    </li>
    
  </ul>
  <div class="tab-content tab-bordered" id="myTab3Content">
    <div class="tab-pane fade show active" id="home2" role="tabpanel" aria-labelledby="home-tab2">
      
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Tuition Fee Categories</h4>
            <div class="card-header-action">
              <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add Category
              </button>
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for category in categories %}
                <tr>
                    <td>{{ category.title }}</td>
                    <td>{{ category.description }}</td>
                    <td><a href="{% url 'finance:fee_list' category.id school_id %}" class="btn btn-primary"><i class="fas fa-hand-holding-usd"></i></a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    
    </div>
    <div class="tab-pane fade" id="profile2" role="tabpanel" aria-labelledby="profile-tab2">
      
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Additional Fee Structure</h4>
            <div class="card-header-action">
              <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal1">
                Add Fee
              </button>
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                    <th>Title</th>
                    <th>amount</th>
                    <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for fee in other_fees %}
                <tr>
                    <td>{{ fee.fee_title }}</td>
                    <td>{{ fee.fee_amount }} {{fee.period}}</td>
                    <td><a href="{% url 'finance:other_fee_payments' fee.id school_id %}" class="btn btn-primary"><i class="fas fa-hand-holding-usd"></i>Payments</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>


</div>
</section>

<!-- Add student modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add Fee Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form id="" method="post" class="">
          {% csrf_token %}
          <div class="modal-body">
            <label for="id_title">Category Title</label>
            <input id="id_title" type="text" name="title" class="form-control" required>
            <label for="id_description">Category Description</label>
            <textarea id="id_description" type="text" name="description" class="form-control" required></textarea>
          </div>
          <div class="modal-footer bg-whitesmoke br">
            <button id="submit_btn" type="submit" name="cate" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add Fee</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <form id="" method="post" class="">
          {% csrf_token %}
          <div class="modal-body">
            {{form}}
          </div>
          <div class="modal-footer bg-whitesmoke br">
            <button id="submit_btn" type="submit" name="other" class="btn btn-primary">Save</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
  


</script>
{% endblock %}

templates/templates/finance/fee_confirm_delete.html
<h1>Are you sure you want to delete this fee?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm</button>
        <a href="{% url 'fee_list' %}">Cancel</a>
    </form>

templates/templates/finance/fee_payments.html

{% extends 'templates/main/base.html' %}

{% block title %}
employees list
{% endblock %}

{% block content %}
<section class="section">
<div class="section-body">
<div class="row">
    <div class="col-12">
      {% if is_other %}
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Payments for {{fee.fee_title}} | MK{{fee.fee_amount}}</h4>
            <div class="card-header-action">
            <span class="badge {% if fee.closed %} badge-danger {% else %} badge-success {% endif %}"><i class="fa fa-circle"></i></span>
            <a href="{% url 'finance:add_other_payment' fee.id school_id %}" class="btn btn-sm btn-primary">Add Payment</a>
              
              <!-- <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add Payment
              </button> -->
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                    <th>Student</th>
                    <th>Paid Amount</th>
                    <th>Date </th>
                    <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for payment in fee.other_fee_payments.all %}
                <tr>
                    <td>{{ payment.student }}</td>
                    <td>{{ payment.amount_paid }}</td>
                    <td>{{ payment.payment_date }}</td>
                    <td><a href="{% url 'student:student' payment.student.id school_id %}" class="btn btn-sm btn-primary">View Student</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      {% else %}
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Fee payments for {{category}}</h4>
            <div class="card-header-action">
            <span class="badge {% if fee.closed %} badge-danger {% else %} badge-success {% endif %}"><i class="fa fa-circle"></i></span>
            <a href="{% url 'finance:add_payment' category.id fee.id school_id %}" class="btn btn-sm btn-primary">Add Payment</a>
              
              <!-- <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add Payment
              </button> -->
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                    <th>Student</th>
                    <th>Academic Year</th>
                    <th>Term</th>
                    <th>Paid Amount</th>
                    <th>Date </th>
                    <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for payment in fee.fee_payments.all %}
                <tr>
                    <td>{{ payment.student }}</td>
                    <td>{{ payment.academic_year }}</td>
                    <td>{{ payment.term }}</td>
                    <td>{{ payment.amount_paid }}</td>
                    <td>{{ payment.payment_date }}</td>
                    <td><a href="{% url 'student:student' payment.student.id school_id %}" class="btn btn-sm btn-primary">View Student</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
</section>

<!-- Add student modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Add Fee Payment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if fee.closed %}
      <div class="modal-body">
        <p>This fee collection point is closed</p>
        <p>Creat new fee collection point to collect fees</p>
      </div>
      {% else %}
      <form id="" method="post" class="">
        {% csrf_token %}
        <div class="modal-body">
          <label for="student">Student:</label>
          <select name="student_id" id="student" class="form-control select2" style="width: fit-content;" required>
            <option value="">-----------</option>
            {% for enrollment in category.enrollment.all %}
              <option value="{{enrollment.student.id}}">{{enrollment.student}}</option>
            {% endfor %}
          </select>
          {{ form }}
        </div>
        <div class="modal-footer bg-whitesmoke br">
          <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

{% block scripts %}
<script>
  
  $('#id_employee').on('change', function(){
    $.ajax({
            type:'POST',
            url:'',
            data: {
                employee:$('#id_employee').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        
            },
            success: function(data){
              $('#id_salary').val(`${data.salary}`);
            },
    });
  });

</script>
{% endblock %}

templates/templates/finance/invoice_form.html
{% extends 'templates/main/base.html' %}

{% block title %}
employees list
{% endblock %}

{% block content %}
<section class="section">
<div class="section-body">
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Add Salary Payment</h4>
            <div class="card-header-action">
            <span class="badge {% if fee.closed %} badge-danger {% else %} badge-success {% endif %}"><i class="fa fa-circle"></i></span>
            <!-- <a href="" class="btn btn-sm btn-primary">Add Payment</a> -->
              
              <!-- <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Add Payment
              </button> -->
            </div>
        </div>
        <div class="card-body">
            <form id="" method="post" class="">
                {% csrf_token %}
                <div class="modal-body">
                    <label for="id_student">Student</label>
                    <select name="student" id="id_student" class="form-control select2" required>
                      <option value="">Select Student</option>
                      {% for student in students %}
                        <option value="{{student.id}}">{{student}}</option>
                      {% endfor %}
                    </select>

                    <label for="id_fee">Tuition Fee</label>
                    <select name="fee" id="id_fee" class="form-control select2" required>
                      <option value="">Select Tuition Fee</option>
                      {% for fee in fees %}
                        <option value="{{fee.id}}">{{fee}}</option>
                      {% endfor %}
                    </select>

                    <label for="id_other_fee">Other Fees</label>
                    <select name="other_fee" id="id_other_fee" class="form-control select2" multiple="">
                      
                      {% for fee in other_fees %}
                        <option value="{{fee.id}}">{{fee}}</option>
                      {% endfor %}
                    </select>

                    <label for="id_issue_discount">Issue Discount</label>
                    <input type="checkbox" name="issue_discount" id="id_issue_discount" class="">

                    <label for="id_percentage">Discount Percentage</label>
                    <input type="number" name="percentage" class="form-control">
                    
                    {{form}}
                </div>
                <div class="modal-footer bg-whitesmoke br">
                    <button class="btn btn-primary" type="submit" name="add-onother">Save and add onother</button>
                    <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
                    <a href="../{{school_id}}" type="button" class="btn btn-secondary">Back</a>
                </div>
            </form>


            
            <!-- <form id="" method="post" class="">
              {% csrf_token %}
              <div class="modal-body">
                <label for="student">Employee:</label>
                <select name="employee" id="id_employee" class="form-control select2" required>
                  <option value="">-----------</option>
                  {% for employee in employees %}
                    <option value="{{employee.id}}">{{employee}}</option>
                  {% endfor %}
                </select>
                <div id="cont" class="container mt-2">
                    
                </div>
                {{ form }}
              </div>
              <div class="modal-footer bg-whitesmoke br">
                <button class="btn btn-primary" type="submit" name="add-onother">Save and add onother</button>
                <button id="submit_btn" type="submit" class="btn btn-primary">Save</button>
                <a href="../{{school_id}}" type="button" class="btn btn-secondary">Back</a>
              </div>
            </form> -->
        </div>
      </div>
    </div>
  </div>
</div>
</section>
{% endblock %}

{% block scripts %}
<script>
  
  $('#id_employee').on('change', function(){
    $.ajax({
            type:'POST',
            url:'{% url "finance:payroll_add" school_id %}',
            data: {
                employee:$('#id_employee').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        
            },
            success: function(data){
              $('#id_salary').val(`${data.salary}`);
              $('#id_allowances').val(`${data.allowance}`);
              $('#id_dedactions').val(`${data.deductions}`);
            },
    });
  });

</script>
{% endblock %}