ZSMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('landing_page.urls')),
    path('student-attendance/', include('attendance.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers-mangement/', include('teacher.urls')),
    path('students-mangement/', include('student.urls')),
    path('class-mangement/', include('classroom.urls')),
    path('library/', include('library.urls')),
    path('timetable/', include('timetable.urls')),
    path('adminstration/', include('schooladminstration.urls')),
    path('employee-management/', include('employee.urls')),
    path('finance-management/', include('finance.urls')),
    path('exam-management/', include('exams.urls')),
    path('school-calendar/', include('school_calendar.urls')),
    path('', include('subscription.urls')),
    path('parent/', include('parent.urls')),
    path('', include('text_to_voice.urls')),
    path('chat', include('chatapp.urls')),
    path('', include('search.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/urls.py
from django.urls import path
from .views import *

app_name='attendance'
urlpatterns = [
    path('subjects/student-attendance-<int:s_id>-<int:c_id>-<uuid:school_id>/', mark_student_attendance, name='attendance'),
    path('student-attendance-list-<uuid:school_id>/', student_attendance_list, name='student_attendance_list'),
    path('student-attendance-list/<int:atte_id><int:clas_id><int:sub_id>-<uuid:school_id>/', student_subject_attendance_list, name='student_sub_attendance_list'),
]

library/urls.py
from django.urls import path
from . import views

app_name='library'
urlpatterns = [
    path('books-<uuid:school_id>/', views.books, name='book_list'),
    path('books/book-copies-<int:book_id>-<uuid:school_id>/', views.book_copies, name='book_copies'),
    path('books/book-copies-<int:book_id>/checkout-<int:copy_id>-<uuid:school_id>/', views.book_checkout, name='checkout'),
    path('book-checkouts-<uuid:school_id>/', views.checkouts, name='checkouts'),
    # path('delete/<int:pk>/', views.employee_delete, name='employee_delete'),
]

main/urls.py
from django.urls import path
from .views import *

app_name='main'
urlpatterns = [
    path('dashboard-<uuid:school_id>/', dashboard, name='dashboard'),
    path('my-profile-<uuid:school_id>/', MyProfile, name='profile'),
    path('account-waiting-approval-<uuid:school_id>/', un_approved, name='un_approved'),
    path('un-authorise-access-<uuid:school_id>/', un_authorised, name='un_authorised'),
    path('add-data/<slug:title>-<uuid:school_id>/', add_data, name='add_data'),
    path('notices-board-<uuid:school_id>/', notice_board, name='notice_board'),    
]

student/urls.py
from django.urls import path
from .views import *

app_name='student'
urlpatterns = [
    path('students-<uuid:school_id>/', students, name='students'),
    path('students/add-enroll-<uuid:school_id>/', student_form, name='student_form'),
    path('students/<int:stu_id>-<uuid:school_id>/', single_student, name='student'),
    path('students/update/<int:stu_id>-<uuid:school_id>/', student_update, name='update'),
    path('student/exams-<int:student_id>-<uuid:school_id>/', exams, name='exams'),
    path('student/exam-result-<int:student_id>-<uuid:school_id>/', exam_result, name='exam_result'),
    path('student/attendance-<int:student_id>-<uuid:school_id>/', attendance, name='atte'),
    path('student/assignments-<int:student_id>-<uuid:school_id>/', assignments, name='ass'),
    path('student/book-checkouts-<int:student_id>-<uuid:school_id>/', book_checkouts, name='check_outs')
]

teacher/urls.py
from django.urls import path
from .views import *


app_name='teacher'
urlpatterns = [
    # teachers urls
    path('teachers-<uuid:school_id>/', teachers, name='teachers'),
    path('teacher-requests-<uuid:school_id>/', teacher_requests, name='teacher_requests'),
    path('teachers/teacher-<int:t_id>-<uuid:school_id>/', single_teacher, name='teacher'),
    path('lesson-plan-list-<uuid:school_id>/', lesson_plan_list, name='lesson_plan_list'),
    path('lesson-plan-list/<int:pk>-<uuid:school_id>/', lesson_plan_detail, name='lesson_plan_detail'),
    path('lesson-plan-list/new/', lesson_plan_create, name='lesson_plan_create'),
    path('lesson-plan-list/<int:pk>/edit-<uuid:school_id>/', lesson_plan_update, name='lesson_plan_update'),
    path('lesson-plan-list/<int:pk>/delete-<uuid:school_id>/', lesson_plan_delete, name='lesson_plan_delete'),

    path('assignments/<int:pk>/submit-<uuid:school_id>/', submission_create, name='submission_create'),
    path('gradebook-<uuid:school_id>/', gradebook_list, name='gradebook_list'),
    path('gradebook/<int:pk>-<uuid:school_id>/', gradebook_detail, name='gradebook_detail'),
    
    path('assignments-<uuid:school_id>/', assignments, name='ass'),
    path('assignments/results-<int:pk>-<uuid:school_id>/', assignment_results, name='ass_results'),
    path('assignments/results/add-<int:pk>-<uuid:school_id>/', add_assignment_result, name='add_ass_results'),
    path('class-work-<uuid:school_id>/', class_works, name='work'),
    path('class-work/results-<int:pk>-<uuid:school_id>/', class_work_result, name='work_results'),
    path('class-work/results/add-<int:pk>-<uuid:school_id>/', add_class_work_result, name='add_work_results'),
    # path('items/<int:pk>/', ItemRetrieveUpdateDestroyView.as_view(), name='item-retrieve-update-destroy'),
]

timetable/urls.py
from django.urls import path
from .views import *

app_name='timetable'
urlpatterns = [
    path('all-time-tables-<uuid:school_id>/', time_tables, name='time_tables'),
    path('time-table/<int:table_id>-<uuid:school_id>/', time_table, name='time_table'),
    path('class-time-table/<int:table_id>-<uuid:school_id>/', inclass_time_table, name='inclass_time_table'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from attendance.models import StudentAttendance
from classroom.forms import ClassForm
from classroom.models import ClassRoom
from employee.models import Employee
from finance.models import Expense, Fee, FeePayment, Income, OtherFee
from finance.utils import total_balance, total_balance_this_month, total_expense_this_month, total_fee_this_month, total_income_this_month, total_other_income_month
from library.models import Book, BookCopy, Checkout
from notifications.forms import NoticeForm
from notifications.models import Notice
from school_calendar.forms import AcademicYearForm, TermForm
from school_calendar.models import AcademicYear, CalendarEvent, Term
from schooladminstration.forms import DepartmentForm, SchoolAddressForm
from staff_permision.permisions import can_manage_employees, can_manage_finances, can_manage_library, is_supper_admin
from student.models import Student
from subscription.models import SchoolSubscription
from teacher.forms import InstructorProfileForm
from teacher.models import LessonPlan
from timetable.models import TimeTable

from .utils import *
from django.http import JsonResponse
from main.utils import *
from datetime import datetime
from accounts.forms import CustomUserCreationForm, UpdateCustomUserForm, UserProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages

# Create your views here.
#redirect to waiting approval page
@login_required
def un_approved(request, school_id):
    # if request.user.parent:
    #     return redirect('parent:dash')
    if is_approved_account(request): return redirect('main:dashboard', school_id)
    institution=get_institution(request, school_id)
    cont={
        'institution':institution,
        'school_id':school_id,
    }
    return render(request, 'templates/main/un_approved_account.html', cont)

@login_required
def un_authorised(request, school_id):
    institution=get_institution(request, school_id)
    cont={
        'institution':institution,
        'school_id':school_id,
    }
    return render(request, 'templates/main/un_authrised.html', cont)



@login_required
def add_data(request, title, school_id):
    institution=get_institution(request, school_id)
    form = None
    card_title=None
    if title == 'add_academic_year':
        if institution.academic_year.all():
            return redirect('main:add_data', 'add_current_term', school_id)
        form = AcademicYearForm()
        card_title='add current academic year'
        if request.method == 'POST':
            form = AcademicYearForm(request.POST)
            if form.is_valid():
                d=form.save(commit=False)
                d.institution=institution
                d.save()
                return redirect('main:add_data', 'add_current_term', school_id)
            
    if title == 'add_current_term':
        if institution.terms.all():
            return redirect('main:add_data', 'add_contact_details', school_id)
        form = TermForm()
        academic_year=AcademicYear.objects.get(institution=institution, closed=False)
        card_title=f'Add current term/semister for {academic_year}'
        if request.method=='POST':
            form = TermForm(request.POST)
            if form.is_valid():
                d=form.save(commit=False)
                d.institution=institution
                d.academic_year=academic_year
                d.save()
                return redirect('main:add_data', 'add_contact_details', school_id)
            
            
    if title == 'add_contact_details':
        if institution.contact_details.all():
            return redirect('main:dashboard', school_id)
        form=SchoolAddressForm()
        card_title=f'Add Contact details'
        if request.method=='POST':
            form=SchoolAddressForm(request.POST)
            if form.is_valid():
                d=form.save(commit=False)
                d.school=institution
                d.save()
                return redirect('main:dashboard', school_id)
    cont={
        'institution':institution,
        'card_title':card_title,
        'form':form,
        'school_id':school_id,
        'institution':institution
    }
    return render(request, 'templates/main/add_data.html', cont)


@login_required
def dashboard(request, school_id):
    if is_approved_account(request): pass
    else: return redirect('main:un_approved', school_id)
    
    institution=get_institution(request, school_id)
    if institution.academic_year.all(): pass 
    else: return redirect('main:add_data', 'add_academic_year', school_id)
    if institution.terms.all():pass
    else: return redirect('main:add_data', 'add_current_term', school_id)
    
    try: 
        if institution.subscription: pass 
    except: return redirect('subs:subscription_plans', school_id)
    
    academic_year=AcademicYear.objects.get(institution=institution, closed=False)
    sub=SchoolSubscription.objects.get(school=institution)
    
    students=Student.objects.filter(school=institution)[0:8]
    teachers=Instructor.objects.filter(school=institution, approved=True)[0:8]
    teacher_requests=Instructor.objects.filter(school=institution, approved=False)
    classes=ClassRoom.objects.filter(school=institution)[0:8]
    attendance_list=StudentAttendance.objects.filter(school=institution).order_by('-date')[0:8]
    isadmin=False
    isclassteacher=False
    isribrarian=False
    ishr=False
    isaccountant=False
    if is_supper_admin(request):
        isadmin=True
    if can_manage_employees(request):
        ishr=True

    events=CalendarEvent.objects.filter(institution=institution).order_by('-start_date')[:3]
    #accountant dashboard
    fee_payments=FeePayment.objects.filter(school=institution).order_by('-payment_date')[0:6]
    incomes=Income.objects.filter(academic_year=academic_year)
    expenses=Expense.objects.filter(academic_year=academic_year)
    if can_manage_finances(request):
        isaccountant=True
    if is_class_teacher(request):
        isclassteacher=True

    #librarian dashboard
    all_books=0
    all_copies=0
    all_checked_out=0
    all_available=0
    book_copies=BookCopy.objects.filter(school=institution)
    book_list=Book.objects.filter(school=institution)
    checkouts=Checkout.objects.filter(school=institution).order_by('-checkout_date')
    if can_manage_library(request):
        all_books=Book.objects.filter(school=institution).count()
        all_copies=BookCopy.objects.filter(school=institution).count()
        all_checked_out=Checkout.objects.filter(school=institution, returned_date__isnull=True).count()
        all_available=all_copies-all_checked_out
        isribrarian=True

    time_table=TimeTable.objects.all()
    day_of_week=datetime.today().weekday()
    days = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    day = days[day_of_week]

    class_teacher=get_class_teacher(request)
    class_attendance_list=None
    classi=None
    classi_students=None
    lesson_plans=None
    if class_teacher:
        classi=ClassRoom.objects.get(teacher_assigned=class_teacher)
        lesson_plans = LessonPlan.objects.filter(teacher=class_teacher).order_by('-date')[0:8]
        class_attendance_list=StudentAttendance.objects.filter(class_room=classi).order_by('-date')[0:8]
        classi_students=classi.students.all()[0:8]
        
    employees=Employee.objects.filter(school=institution)
    
    term=Term.objects.get(institution=institution, closed=False)
    
    current_fees=Fee.objects.filter(school=institution)
    other_fees=OtherFee.objects.filter(school=institution)
  
    notes=Notice.objects.filter(school=institution).order_by('-created_at')
    date=datetime.today().date()
    cont={
        'students':students,
        'teachers':teachers,
        'classes':classes,
        'day':day,
        'is_admin':isadmin,
        'is_class_teacher':isclassteacher,
        'class':classi,
        'class_attendance_list':class_attendance_list,
        'attendance_list':attendance_list,
        'class_students':classi_students,
        'lesson_plans':lesson_plans,
        'is_teacher':is_teacher(request),
        'teacher_requests':teacher_requests,
        'current_fees':current_fees,

        'total_fees_this_month':total_fee_this_month(institution, date),
        'total_other_income_month':total_other_income_month(institution, date),
        'total_income_month':total_income_this_month(institution, date),
        'total_expense_month':total_expense_this_month(institution, date),
        'total_balance':total_balance(institution),


        # 'total_fees':total_fee_collected,
        # 'total_fee_year':total_fee_collected_this_year,
        # 'total_income_year':total_income_this_year,
        # 'total_expense_year':total_expense_this_year,
        # 'employees':employees,
        # 'overall_income':overall_income,
        # 'overall_expense':overall_expense,
        # 'total_expense':total_expense,
        # 'balance':overall_income-total_expense,
        
        
        'academic_year':academic_year,
        'is_hr':ishr,

        #accountant
        'fee_payments':fee_payments,
        'is_accountant':isaccountant,
        'expenses':expenses,
        'incomes':incomes,

        #hr manager
        'employees':employees,

        #librarian
        'is_librarian':isribrarian,
        'all_books':all_books,
        'all_copies':all_copies,
        'all_checked_out':all_checked_out,
        'all_available':all_available,
        'book_copies':book_copies,

templates/templates/main/dashboards/admin.html
  <div class="row">
    <div class="col-12 col-sm-12 col-lg-12">
      


      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">Class schedules({{day|title}})</h4>
            <div class="card-header-action">
              <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Create Timetable
              </button>
            </div>
        </div>
        <div class="card-body">
          
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                  <th>Class Room</th>
                  <th>Subjects</th>
                  <!-- <th>Action</th> -->
                </tr>
              </thead>
              <tbody>
                {% for class in classes %}
                <tr class="border border-success">

                        <td>{{class}}</td>
                        {% for timetable in class.timetable.all %} 
                        {% for subject in timetable.timetable_subjects.all %} 
             
                          {% if subject.day == day %}
                            <td class=" border border-success">
                              {{ subject.start_time }} - {{ subject.end_time }} <br>
                              {{ subject.subject }}
                            </td>
                          {% endif %}
                        {% endfor %}
                        <td><a href="{% url 'timetable:time_table' timetable.id school_id %}" class="btn btn-outline-primary">
                          View full
                        </a></td>
                        {% endfor %}
                        
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
 
        </div>
      </div>


      <div class="card">
        <div class="card-header">
            <h4 class="d-inline"> Students Attendance</h4>
            <!-- <div class="card-header-action">
              <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Students Attendance
              </button>
            </div> -->
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" id="save-stage" style="width:100%;">
              <thead>
                <tr>
                  <th>CLass & Subject</th>
                  <th>Date</th>
                  <th>Attended</th>
                  <th>Absent</th>
                  <th>Late</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for d in attendance_list %}
                <tr>
                    <td>
                        {{d.class_room}} - {{d.subject}}
                    </td>
                    <td>
                      {{d.date.date}} <br>
                      {{d.date.time}}
                    </td>
                    <td>
                        {{d.students_attended}}
                    </td>
                    <td>
                      {{d.students_absent}}
                    </td>
                    <td>
                      {{d.students_late}}
                  </td>
                    <td><a href="{% url 'attendance:student_sub_attendance_list' d.id d.class_room.id d.subject.id school_id %}" class="btn btn-primary">view</a></td>

                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>


<div class="card">
<div class="card-header">
    <h4 class="d-inline">Students List</h4>
    <div class="card-header-action">
      <a href="{% url 'student:students' school_id %}" class="btn btn-primary">View all students</a>

    </div>
</div>
<div class="card-body">
  <div class="table-responsive">
    <table class="table table-striped table-hover" id="" style="width:100%;">
      <thead>
        <tr>
          <th>Name</th>
          <th>Gender</th>
          <th>ID #</th>
          <th>Class</th>
          <th>Date Enrolled</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr>
          <td>{{student.first_name}} {{student.last_name}}</td>
          <td>{{student.gender}}</td>
          <td>{{student.id_number}}</td>
          <td>
            {% for n in student.class_students.all %}
            {{n.class_name}}</td>
            {% endfor %}
          <td>
            {% for n in student.enrollement.all %}
              {{n.start_date}} <br>
              <span class="badge badge-success badge-rounded">{{n.status}}</span>
            {% endfor %}
          </td>
          <td><a href="{% url 'student:student' student.id school_id %}" class="btn btn-primary">View</a> <a href="#" class="btn btn-danger">Del</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>

<div class="card">
<div class="card-header">
    <h4 class="d-inline">Teachers</h4>
    <div class="card-header-action">
      <a href="{% url 'teacher:teachers' school_id %}" class="btn btn-primary">View all teachers</a>

    </div>
</div>
<div class="card-body">
  <div class="table-responsive">
    <table class="table table-striped table-hover" id="" style="width:100%;">
      <thead>
        <tr>
          <th>Name</th>
          <th>Gender</th>
          <th>Department</th>
          <th>Phone</th>
          <th>Date Started</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for teacher in teachers %}
        <tr>
          <td>{{teacher.first_name}} {{student.last_name}}</td>
          <td>{{teacher.gender}}</td>
          <td>{{teacher.department}}</td>
          <td>{{teacher.phone}}</td>
          <td>{{teacher.date_started}}</td>
          <td><a href="{% url 'teacher:teacher' teacher.id school_id %}" class="btn btn-primary">View</a> <a href="#" class="btn btn-danger">Del</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
</div>
      
    
      
    </div>
</div>

templates/templates/main/dashboards/class_teacher.html
  
  <div class="row">
    <div class="col-12 col-sm-12 col-lg-12">
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">{{class}} Class schedules({{day|title}})</h4>
            <div class="card-header-action">
              <!-- <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Create Timetable
              </button> -->
            </div>
        </div>
        <div class="card-body">
          
          <div class="table-responsive">
            <table class="table table-striped table-hover" style="width:100%;">
              <thead>
                <tr>
                  <th>Subjects</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                
                <tr>
  
                        
                        {% for timetable in class.timetable.all %} 
                        {% for subject in timetable.timetable_subjects.all %} 
             
                          {% if subject.day == day %}
                            <td>
                              {{ subject.start_time }} - {{ subject.end_time }} <br>
                              {{ subject.subject }}
                            </td>
                          {% endif %}
                        {% endfor %}
                        <td><a href="{% url 'timetable:time_table' timetable.id school_id %}" class="btn btn-outline-primary">
                          View full
                        </a></td>
                        {% endfor %}
                        
                </tr>
                
              </tbody>
            </table>
          </div>
  
        </div>
      </div>
  
  
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">{{class}} Students Attendance</h4>
            <!-- <div class="card-header-action">
              <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Students Attendance
              </button>
            </div> -->
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" id="save-stage" style="width:100%;">
              <thead>
                <tr>
                  <th>Subject</th>
                  <th>Date</th>
                  <th>Attended</th>
                  <th>Absent</th>
                  <th>Late</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for d in class_attendance_list %}
                <tr>
                    <td>
                        {{d.subject}}
                    </td>
                    <td>
                      {{d.date.date}} <br>
                      {{d.date.time}}
                    </td>
                    <td>
                        {{d.students_attended}}
                    </td>
                    <td>
                      {{d.students_absent}}
                    </td>
                    <td>
                      {{d.students_late}}
                  </td>
                    <td><a href="{% url 'attendance:student_sub_attendance_list' d.id d.class_room.id d.subject.id school_id %}" class="btn btn-primary">view</a></td>
  
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
  
  
      <div class="card">
        <div class="card-header">
            <h4 class="d-inline">{{class}} Students List</h4>
            <div class="card-header-action">
              <a href="{% url 'student:students' school_id %}" class="btn btn-primary">View all students</a>
  
            </div>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped table-hover" id="" style="width:100%;">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Gender</th>
                  <th>ID #</th>
                  <th>Date Enrolled</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {% for student in class_students %}
                <tr>
                  <td>{{student.first_name}} {{student.last_name}}</td>
                  <td>{{student.gender}}</td>
                  <td>{{student.id_number}}</td>
                 
                  <td>
                    {% for n in student.enrollement.all %}
                      {{n.start_date}} <br>
                      <span class="badge badge-success badge-rounded">{{n.status}}</span>
                    {% endfor %}
                  </td>
                  <td><a href="{% url 'student:student' student.id school_id %}" class="btn btn-primary">View</a> <a href="#" class="btn btn-danger">Del</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
  
      
    </div>
  </div>
  

templates/templates/main/dashboards/for_all.html
<div class="card">
    <div class="card-header">
        <h4 class="d-inline">Notice Board</h4>
        <div class="card-header-action">
          <a href="{% url 'main:notice_board' school_id %}" class="btn btn-primary">
            View all
          </a>
        </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-hover" id="" style="width:100%;">
          <thead>
            <tr>
              <th>Title</th>
              <th>Audience</th>
              <th>Posted By</th>
              <!-- <th>Content</th> -->
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for note in notices %}
            
            <tr class="{% if employee.needs_attention %} bg-warning {% endif %}">
              <td>{{note.title}}</td>
              <td>{{note.audience}}</td>
              <td>{{note.posted_by}} <br>
                    on {{note.created_at}}
              </td>
              
              <td><a href="" class="btn btn-primary">Content</a> </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>



<div class="card">
    <div class="card-header">
        <h4 class="d-inline">Upcoming Events</h4>
        <div class="card-header-action">
          <a class="btn btn-primary" href="{% url 'school_calendar:events' school_id %}">
            View all
          </a>
        </div>
    </div> 
    <div class="card-body">
      
      <div class="table-responsive">
        <table class="table table-striped table-hover" id="" style="width:100%;">
          <thead>
            <tr>
              <th>Title</th>
              <th>Type</th>
              <th>Status</th>
              <!-- <th>End Date</th> -->
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for event in events %}
            
            <tr>
              <td>{{event.title}}</td>

              <td>{{event.event_type}} 
              </td>
              <td>
                {% if event.is_ongoing %}
                <span class="badge badge-pill badge-success">On-going</span>
                {% elif event.passed_day %}
                  <span class="badge badge-pill badge-secondary">Occured</span>
                {% else %}
                  <span class="badge badge-pill badge-info">{{event.remaining_day}} Days to go</span>
                {% endif %}</td>
              <!-- <td>{{event.end_date}}</td> -->
              <td><a href="{% url 'school_calendar:event_detail' event.id school_id %}" class="btn btn-primary">View</a> <a href="#" class="btn btn-danger">Del</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>
  </div>

templates/templates/main/dashboards/teacher.html
<div class="card">
    <div class="card-header">
        <h4 class="d-inline">My Lesson Plans</h4>
        <div class="card-header-action">
          <button id="show_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            View all Lesson Plans
          </button>
        </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-hover" id="save-stage" style="width:100%;">
          <thead>
            <tr>
              <th>Title</th>
              <th>Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for lesson_plan in lesson_plans %}
            <tr>
              <td>{{lesson_plan.title}}</td>
              <td>{{lesson_plan.date}}</td>
              <td><a href="{% url 'teacher:lesson_plan_detail' lesson_plan.id %}" class="btn btn-primary">View</a> <a href="#" class="btn btn-danger">Del</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  
  