ZSMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('landing_page.urls')),
    path('student-attendance/', include('attendance.urls')),
    path('accounts/', include('accounts.urls')),
    path('teachers-mangement/', include('teacher.urls')),
    path('students-mangement/', include('student.urls')),
    path('class-mangement/', include('classroom.urls')),
    path('library/', include('library.urls')),
    path('timetable/', include('timetable.urls')),
    path('adminstration/', include('schooladminstration.urls')),
    path('employee-management/', include('employee.urls')),
    path('finance-management/', include('finance.urls')),
    path('exam-management/', include('exams.urls')),
    path('school-calendar/', include('school_calendar.urls')),
    path('', include('subscription.urls')),
    path('parent/', include('parent.urls')),
    path('', include('text_to_voice.urls')),
    path('chat', include('chatapp.urls')),
    path('', include('search.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from re import template
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp, name='signup'),
    path('login/', Login, name='login'),
    path('profile-selection/', profile_select_view, name='profile_select'),
    path('create', create_teacher, name='create_teacher'),

    path('confirm_email', Confirm_signup, name='confirm_si'),
    path('email_confirmed', Confirmed_signup, name='confirmed_si'),
    path('logout', logout_view, name='logout'),
    path('school-profiles', school_profiles, name='school_p'),
    # path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('password_reset/', ForgetPassword, name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"), name='password_reset_confirm'),
    ]

landing_page/urls.py
from django.urls import path
from .views import *
app_name='landing_page'

urlpatterns =[
    path('', index, name='landing'),
    # path('testimonials/', testimonials_view, name='testimonials'),
    path('pricing/', pricing, name='pricing'),
    path('features/', system_features, name='s_features'),
    path('features/feature-<int:f_id>/', system_feature, name='s_feature'),
    path('contact-us/', contact_us, name='contact'),
    path('About-us/', about, name='about'),
    path('fequent-asked-questions/', faqs, name='faqs'),
    path('terms-and-conditions/', terms, name='terms'),
    path('prpivacy-policy/', privacy, name='privacy'),
]

landing_page/views.py
from django.shortcuts import render
from subscription.models import SubscriptionPlan, Feature
from system_admin.models import About, Faqs, Privacy, SystemFeature, Contact, Terms
# Create your views here.
def index(request):
    plans=SubscriptionPlan.objects.all()
    features=Feature.objects.all()
    system_features=SystemFeature.objects.all()
    about=About.objects.first()
    cont={
        'plans':plans,
        'features':features,
        'system_features':system_features,
        'about':about
    }
    return render(request, 'templates/landing_page/index.html', cont)

def system_features(request):
    system_features=SystemFeature.objects.all()
    cont={
        'system_features':system_features
    }
    return render(request, 'templates/landing_page/features.html', cont)

def system_feature(request, f_id):
    feature=SystemFeature.objects.get(id=f_id)
    features=SystemFeature.objects.all()
    cont={
        'feature':feature,
        'features':features
    }
    return render(request, 'templates/landing_page/feature.html', cont)

def pricing(request):
    plans=SubscriptionPlan.objects.all()
    features=Feature.objects.all()
    cont={
        'plans':plans,
        'features':features,
    }
    return render(request, 'templates/landing_page/pricing.html', cont)

def contact_us(request):
    if request.method=='POST':
        name=request.POST.get('full_name')
        email=request.POST.get('email')
        phone=request.POST.get('phone')
        message=request.POST.get('message')
        d=Contact()
        d.name=name
        d.email=email
        d.phone=phone
        d.message=message
        d.save()
        return render(request, 'templates/landing_page/thank_you.html')
    cont={
       
    }
    return render(request, 'templates/landing_page/contact_us.html', cont)

def about(request):
    about=About.objects.first()
    cont={
       'about':about
    }
    return render(request, 'templates/landing_page/about.html', cont)

def terms(request):
    terms=Terms.objects.first()
    cont={
       'terms':terms
    }
    return render(request, 'templates/landing_page/terms.html', cont)

def privacy(request):
    privacy=Privacy.objects.first()
    cont={
       'privacy':privacy
    }
    return render(request, 'templates/landing_page/privacy.html', cont)

def faqs(request):
    faqs=Faqs.objects.first()
    cont={
       'faqs':faqs
    }
    return render(request, 'templates/landing_page/faqs.html', cont)

templates/templates/landing_page/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <title>Bizz - Business Consulting and Agency HTML Template </title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Calling Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Calling Favicon -->
    <!-- ********************* -->
    <!-- CSS files -->
    <link rel="stylesheet" href="{% static 'assets_landing/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/meanmenu.css' %}" media="all">
    <link rel="stylesheet" href="{% static 'assets_landing/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/style.css' %}">
    <link rel="stylesheet" class="color-changing" href="{% static 'assets_landing/css/color.css' %}">
    <link rel="stylesheet" href="{% static 'assets_landing/css/responsive.css' %}">
    <!-- End CSS files -->
     <style>
        .price-text h3 {
        color: #09bc8a;
        font-size: 32px;
        font-family: 'Montserrat', sans-serif;
        letter-spacing: 0;
        }

        .price-text h3 span {
        color: rgb(66, 62, 62);
        font-size: 14px;
        margin-right: 5px;
        font-weight: 500;
        }
     </style>
</head>

<body>
    {% include 'templates/landing_page/base/header.html' %}

   {% block content %}

   {% endblock %}

   {% include 'templates/landing_page/base/footer.html' %}

    <!-- ********************* -->
    <!-- Theme skins -->
    <div class="color-theme transition-4">
        <div class="theme-switch">
            <span class="switch">
              <i class="fas fa-angle-right"></i>
            </span>
        </div>
        <div class="theme-colors transition-4">
            <h4>Theme Skins:</h4>
            <ul class="theme-ul">
                <li>
                    <span class="each-color co1" data-color="css/color.css">
                        <img src="img/co-1.png" alt="">
                    </span>
                </li>
                <li>
                    <span class="each-color co2" data-color="css/color2.css">
                        <img src="img/co-2.png" alt="">
                    </span>
                </li>
                <li>
                    <span class="each-color co3" data-color="css/color3.css">
                        <img src="img/co-3.png" alt="">
                    </span>
                </li>
                <li>
                    <span class="each-color co4" data-color="css/color4.css">
                        <img src="img/co-4.png" alt="">
                    </span>
                </li>
                <li>
                    <span class="each-color co5" data-color="css/color5.css">
                        <img src="img/co-5.png" alt="">
                    </span>
                </li>
                <li>
                    <span class="each-color co6" data-color="css/color6.css">
                        <img src="img/co-6.png" alt="">
                    </span>
                </li>
            </ul>
            <p class="fs-13 "><b>Note: </b>This will not change any image colors (logo, icon colors..etc)</p>
        </div>
    </div>
    <!-- Theme skins -->
    <!-- JS Files -->
    <script src="{% static 'assets_landing/js/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/lightslider.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/wow.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/jquery.meanmenu.min.js' %}"></script>
    <script src="{% static 'assets_landing/js/main.js' %}"></script>
    <!-- JS Files end -->
</body>

</html>

templates/templates/landing_page/base/footer.html
    <!-- Footer area start -->
    <footer class="footer-area">
        <div class="container">
            <div class="row mb-sm-50 mb-xs-00">
                <div class="col-lg-4 z-5">
                    <div class="contact-area relative h-100 mr-lg-20 mr-md-00">
                        <div class="footer-logo mb-35">
                            <img src="img/logo/logo_footer.png" alt="">
                        </div>
                        <div class="contact-options mb-35">
                            <ul>
                                <li>
                                    <i class="fas fa-map-marker-alt green"></i>Blantyre Malawi
                                </li>
                                <li>
                                    <i class="fas fa-phone green"></i>+265 993 756 436
                                </li>
                                <li>
                                    <i class="fas fa-envelope green"></i>info@zathusystems.com
                                </li>
                            </ul>
                        </div>
                        <div class="social-links">
                            <ul class="social-icons">
                                <li>
                                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                                </li>
                              
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-4">
                    <div class="footer-links pt-85 pt-md-50 mb-sm-70">
                        <h5 class="green f-700 mb-35">Quick Links</h5>
                        <ul class="links-list">
                            <li><a href="{% url 'landing_page:landing' %}">Home</a></li>
                            <li><a href="{% url 'landing_page:about' %}">About Us</a></li>
                            <li><a href="{% url 'landing_page:s_features' %}">Features</a></li>
                            <li><a href="{% url 'landing_page:pricing' %}">Pricing</a></li>
                            {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else  %}
                            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    
                </div>
                <div class="col-lg-3 col-sm-4">
                    <div class="footer-links pt-85 pt-md-50 mb-sm-70">
                        <h5 class="green f-700 mb-35">Our System Features</h5>
                        <ul class="links-list">
                            {% for feature in featuress %}
                            <li><a href="{% url 'landing_page:s_feature' feature.id %}">{{feature}}</a></li>
                            {% endfor %}
                            <li><a href="{% url 'landing_page:s_features' %}">View all</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-4">
                    <div class="footer-links pt-85 pt-md-50 mb-50" >
                        <h5 class="green f-700 mb-35">Need Help?</h5>
                        <ul class="links-list">
                            <li><a href="#"></a></li>
                            <!-- <li><a href="#">Privacy</a></li>
                            <li><a href="#">Policy</a></li> -->
                            <li><a href="#">Support</a></li>
                            <!-- <li><a href="#">Get a Quote</a></li>
                            <li><a href="#">Contact us</a></li> -->
                            <li><a href="{% url 'landing_page:contact' %}">Contact Us</a></li>

                            <li> <a href="{% url 'landing_page:terms' %}">Terms & Conditions </a></li>
                            <li> <a href="{% url 'landing_page:privacy' %}">Privacy Policy </a></li>
                            <li> <a href="{% url 'landing_page:faqs' %}">FAQS </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="copyright pt-25 pb-25">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-8">
                        <p class="mb-0 white">© Copyrights {% now 'Y' %} SchoolMangementOnline By zathuSystems</p>
                    </div>
                    <div class="col-xl-4 text-right">
                        <a href="#" class="btn scroll-btn f-right flex-center z-25 opacity-0">
                            <i class="fas fa-arrow-up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    <!-- Footer area end -->

templates/templates/landing_page/base/header.html
{% load static %}

<!-- Preloader start -->
<div class="loader-page flex-center">
    <img src="{% static 'assets_landing/img/loader.gif' %}" alt="">
</div>
<!-- Preloader end -->

<header class="transperant-head header-style-3 transition-4">
    <div class="container">
        <div class="row align-items-center no-gutters">
            <div class="col-lg-2 col-md-5 col-sm-4 col-5">
                <div class="logo transition-4">
                    <a href="#">
                        <img src="{% static 'assets_landing/img/logo.png' %}" class="transition-4" alt="logo">
                    </a>
                </div>
            </div>
            <div class="col-lg-10 col-md-7 col-sm-8 col-7">
                <div class="icon-links d-flex align-items-center mr-md-30">
                    <a href="#" class="shop-icon d-none d-sm-block">
                        <i class="fas fa-shopping-basket black"></i>
                        <span class="count">2</span>
                    </a>
                    <a href="#" class="search-icon d-none d-sm-block black" data-toggle="modal" data-target="#searchModal">
                        <i class="fas fa-search"></i>
                    </a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'accounts:school_p' %}" class="btn btn-round d-none d-sm-block blob-small">Dashboard</a>
                    {% else  %}
                        <a href="{% url 'accounts:signup' %}" class="btn btn-round d-none d-sm-block blob-small">Get Started</a>
                    {% endif %}
                </div>
                <div class="menu-links links-type-3 float-left">
                    <nav class="main-menu main-menu-3 white">
                        <ul>
                            <li class="active">
                                <a href="{% url 'landing_page:landing' %}">Home </a>
                            
                            </li>
                   
                            <li>
                                <a href="{% url 'landing_page:pricing' %}">Pricing </a>
                               
                            </li>
                            <li>
                                <a href="{% url 'landing_page:s_features' %}">Features </a>
                               
                            </li>
                            <li>
                                <a href="{% url 'landing_page:contact' %}">Contact Us </i></a>
                                
                            </li>
                            <li>
                                <a href="index-2.html">More <i class="fas fa-angle-down"></i></a>
                                <ul class="submenu">
                                    <li> <a href="{% url 'landing_page:about' %}">About Us</a></li>
                                    <li> <a href="{% url 'landing_page:terms' %}">Terms & Conditions </a></li>
                                    <li> <a href="{% url 'landing_page:privacy' %}">Privacy Policy </a></li>
                                    <li> <a href="{% url 'landing_page:faqs' %}">Faq </a></li>
                                </ul>
                            </li>
                            
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-12">
                <div class="mobile-menu-3"></div>
            </div>
        </div>
    </div>

</header>
<!-- The search Modal start -->
<div class="search-popup modal" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <form action="#">
                    <div class="form-group relative">
                        <input type="text" class="form-control input-search" id="search" placeholder="Search here...">
                        <i class="fas fa-search transform-v-center"></i>
                    </div>
                </form>

            </div>
        </div>
    </div>
    <i class="fas fa-times close-search-modal" data-dismiss="modal" aria-label="Close"></i>
</div>
<!-- The search Modal end -->
    <!-- Header end -->
    <!-- Header end -->